# Generated by Django 2.1.5 on 2019-03-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routefinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True, unique=True)),
                ('from_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['from_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaTerrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab', models.FloatField(blank=True, null=True)),
                ('arete', models.FloatField(blank=True, null=True)),
                ('crack', models.FloatField(blank=True, null=True)),
                ('chimney', models.FloatField(blank=True, null=True)),
                ('overhang', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area_terrain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RouteLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelTable(
            name='route',
            table='routes_scored',
        ),
    ]
