# Generated by Django 2.1.5 on 2019-03-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routefinder', '0002_auto_20190307_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaGrades',
            fields=[
                ('id', models.FloatField(blank=True, primary_key=True, serialize=False)),
                ('sport', models.FloatField(blank=True, null=True)),
                ('trad', models.FloatField(blank=True, null=True)),
                ('tr', models.FloatField(blank=True, null=True)),
                ('boulder', models.FloatField(blank=True, null=True)),
                ('mixed', models.FloatField(blank=True, null=True)),
                ('aid', models.FloatField(blank=True, null=True)),
                ('ice', models.FloatField(blank=True, null=True)),
                ('snow', models.FloatField(blank=True, null=True)),
                ('alpine', models.FloatField(blank=True, null=True)),
                ('pitches', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('danger_conv', models.FloatField(blank=True, null=True)),
                ('bayes', models.FloatField(blank=True, null=True)),
                ('rope_conv', models.FloatField(blank=True, null=True)),
                ('boulder_conv', models.FloatField(blank=True, null=True)),
                ('mixed_conv', models.FloatField(blank=True, null=True)),
                ('aid_conv', models.FloatField(blank=True, null=True)),
                ('ice_conv', models.FloatField(blank=True, null=True)),
                ('snow_conv', models.FloatField(blank=True, null=True)),
                ('nccs_conv', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area_grades',
                'managed': False,
            },
        ),
    ]
