# Generated by Django 2.1.5 on 2019-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routefinder', '0003_areagrades'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerrainTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
